//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmacenRopa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUDITORIASTOCK
    {
        public int ID_AUDITORIA { get; set; }
        public System.DateTime FECHA { get; set; }
        public decimal CANTIDAD_REAL { get; set; }
        public int ID_STOCK { get; set; }
        public int ID_EMPLEADO { get; set; }
    
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual STOCK STOCK { get; set; }
    }
}
