//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmacenRopa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLEVENTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DETALLEVENTA()
        {
            this.DETALLEDEVOLUCIONs = new HashSet<DETALLEDEVOLUCION>();
        }
    
        public int ID_DETALLE { get; set; }
        public decimal PRECIO_UNITARIO { get; set; }
        public int ID_VENTA { get; set; }
        public int ID_STOCK { get; set; }
        public int CANTIDAD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLEDEVOLUCION> DETALLEDEVOLUCIONs { get; set; }
        public virtual STOCK STOCK { get; set; }
        public virtual VENTA VENTA { get; set; }
    }
}
