//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmacenRopa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIRECCIONESCLIENTE
    {
        public int ID_DIRECCION { get; set; }
        public string DIRECCION { get; set; }
        public int CIUDAD { get; set; }
        public int TIPO { get; set; }
        public int ID_CLIENTE { get; set; }
    
        public virtual CIUDAD CIUDAD1 { get; set; }
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual TIPO_DIRECCION TIPO_DIRECCION { get; set; }
    }
}
