//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmacenRopa.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ALMACEN_ROPAEntities : DbContext
    {
        public ALMACEN_ROPAEntities()
            : base("name=ALMACEN_ROPAEntities")
        {
            this.Configuration.ProxyCreationEnabled = false; //  Esto evita que EF genere tipos dinámicos
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AUDITORIASTOCK> AUDITORIASTOCKs { get; set; }
        public virtual DbSet<CANAL_VENTA> CANAL_VENTA { get; set; }
        public virtual DbSet<CATEGORIA> CATEGORIAs { get; set; }
        public virtual DbSet<CIUDAD> CIUDADs { get; set; }
        public virtual DbSet<CLIENTE> CLIENTES { get; set; }
        public virtual DbSet<COLOR> COLORs { get; set; }
        public virtual DbSet<DETALLEDEVOLUCION> DETALLEDEVOLUCIONs { get; set; }
        public virtual DbSet<DETALLEPEDIDO> DETALLEPEDIDOes { get; set; }
        public virtual DbSet<DETALLEVENTA> DETALLEVENTAs { get; set; }
        public virtual DbSet<DEVOLUCION> DEVOLUCIONs { get; set; }
        public virtual DbSet<DIRECCIONESCLIENTE> DIRECCIONESCLIENTEs { get; set; }
        public virtual DbSet<EMPLEADO> EMPLEADOS { get; set; }
        public virtual DbSet<HISTORIAL> HISTORIALs { get; set; }
        public virtual DbSet<METODOSPAGO> METODOSPAGOes { get; set; }
        public virtual DbSet<PAGO> PAGOes { get; set; }
        public virtual DbSet<PEDIDO> PEDIDOes { get; set; }
        public virtual DbSet<PRODUCTO> PRODUCTOes { get; set; }
        public virtual DbSet<PRODUCTO_PROVEEDOR> PRODUCTO_PROVEEDOR { get; set; }
        public virtual DbSet<PRODUCTO_VARIANTE> PRODUCTO_VARIANTE { get; set; }
        public virtual DbSet<PROVEEDOR> PROVEEDORs { get; set; }
        public virtual DbSet<RECEPCIONPEDIDO> RECEPCIONPEDIDOes { get; set; }
        public virtual DbSet<SEDE> SEDES { get; set; }
        public virtual DbSet<STOCK> STOCKs { get; set; }
        public virtual DbSet<TALLA> TALLAs { get; set; }
        public virtual DbSet<TIPO_CLIENTE> TIPO_CLIENTE { get; set; }
        public virtual DbSet<TIPO_DIRECCION> TIPO_DIRECCION { get; set; }
        public virtual DbSet<USUARIO> USUARIOs { get; set; }
        public virtual DbSet<VENTA> VENTAS { get; set; }
    }
}
