//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmacenRopa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGO
    {
        public int ID_PAGO { get; set; }
        public System.DateTime FECHA { get; set; }
        public decimal MONTO { get; set; }
        public int ID_VENTA { get; set; }
        public int ID_METODO_PAGO { get; set; }
    
        public virtual METODOSPAGO METODOSPAGO { get; set; }
        public virtual VENTA VENTA { get; set; }
    }
}
