//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmacenRopa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO_VARIANTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTO_VARIANTE()
        {
            this.DETALLEPEDIDOes = new HashSet<DETALLEPEDIDO>();
            this.STOCKs = new HashSet<STOCK>();
        }
    
        public int ID_PRODUCTO_VARIANTE { get; set; }
        public int ID_PRODUCTO { get; set; }
        public int ID_TALLA { get; set; }
        public int ID_COLOR { get; set; }
    
        public virtual COLOR COLOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLEPEDIDO> DETALLEPEDIDOes { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STOCK> STOCKs { get; set; }
        public virtual TALLA TALLA { get; set; }
    }
}
