//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmacenRopa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECEPCIONPEDIDO
    {
        public int ID_RECEPCION { get; set; }
        public System.DateTime FECHA_RECEPCION { get; set; }
        public int ID_PEDIDO { get; set; }
        public int ID_SEDE { get; set; }
        public int ID_EMPLEADO { get; set; }
    
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual PEDIDO PEDIDO { get; set; }
        public virtual SEDE SEDE { get; set; }
    }
}
