//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmacenRopa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STOCK()
        {
            this.AUDITORIASTOCKs = new HashSet<AUDITORIASTOCK>();
            this.DETALLEVENTAs = new HashSet<DETALLEVENTA>();
        }
    
        public int ID_STOCK { get; set; }
        public int CANTIDAD { get; set; }
        public int ID_PRODUCTO_VARIANTE { get; set; }
        public int ID_SEDE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AUDITORIASTOCK> AUDITORIASTOCKs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLEVENTA> DETALLEVENTAs { get; set; }
        public virtual PRODUCTO_VARIANTE PRODUCTO_VARIANTE { get; set; }
        public virtual SEDE SEDE { get; set; }
    }
}
