//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmacenRopa.Models
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;

    public partial class VENTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VENTA()
        {
            this.DETALLEVENTAs = new HashSet<DETALLEVENTA>();
            this.DEVOLUCIONs = new HashSet<DEVOLUCION>();
            this.PAGOes = new HashSet<PAGO>();
        }
    
        public int ID_VENTA { get; set; }
        public System.DateTime FECHA { get; set; }
        public int CANAL { get; set; }
        public Nullable<int> ID_CLIENTE { get; set; }
        public Nullable<int> ID_EMPLEADO { get; set; }

        [JsonIgnore]
        public virtual CANAL_VENTA CANAL_VENTA { get; set; }
        [JsonIgnore]
        public virtual CLIENTE CLIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<DETALLEVENTA> DETALLEVENTAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<DEVOLUCION> DEVOLUCIONs { get; set; }
        [JsonIgnore]
        public virtual EMPLEADO EMPLEADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<PAGO> PAGOes { get; set; }
    }
}
